
+SingularityImage = "osdf:///ospool/uc-shared/public/OSG-Staff/training/ospool-gpu-examples/llm-rag/llm-rag-v1.sif"

request_cpus = 4
request_gpus = 1
request_memory = 5 GB
request_disk = 10 GB

gpus_minimum_capability = 7.0

executable = llm-wrapper.sh

transfer_input_files = llm-rag.py, prompts.txt, docs

Error = logs/$(Cluster).$(Process).error
Output = logs/$(Cluster).$(Process).output
Log = logs/$(Cluster).$(Process).log

queue 1

